data/urls.py
from django.conf.urls import re_path
from . import views
# 使用了二级路由

app_name = 'data'
urlpatterns = [

    re_path(r'^index/', views.index, name='index'),                            # 主页
    re_path(r'^test_page', views.test_page, name='test_page'),                 # 测试页面
    re_path(r'^lists/(?P<table>\w+)/$', views.lists, name='lists'),            # 数据解析页面
    re_path(r'^diagnosis/', views.diagnosis, name='diagnosis'),                # 故障诊断页面
    re_path(r'^engine_fault_code_data/$', views.engine_fault_code_data),       # 全部的故障码数据
    re_path(r'^engine_fault_data_reload/$', views.engine_fault_data_reload),   # 查询的故障码和现象数据

]

mysite/urls.py
from django.urls import re_path, include
from django.contrib import admin
from login import views

urlpatterns = [
    re_path(r'^admin/', admin.site.urls),
    re_path(r'^index/', views.index),
    re_path(r'^login/', views.login),
    re_path(r'^register/', views.register),
    re_path(r'^logout/', views.logout),
    # re_path(r'^captcha', include('captcha.urls')),
    re_path(r'', include('data.urls')),

]

data/models.py
from django.db import models

# 在setting里设置连接mysql数据库djangodata
# 执行python manage.py inspectdb 命令，生成的数据库里所有表格对应的models，复制到这里
class Student(models.Model):
    id = models.IntegerField(primary_key=True)
    name = models.CharField(max_length=255, blank=True, null=True)
    sex = models.CharField(max_length=255, blank=True, null=True)
    age = models.IntegerField(blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'student'


class Tboxdata(models.Model):
    id = models.IntegerField(db_column='key', blank=True, primary_key=True)
    tbox_data = models.TextField(db_column='TBOX_data', blank=True, null=True)  # Field name made lowercase.
    # sdata = models.TextField(blank=True, null=True)
    vin = models.TextField(db_column='VIN', blank=True, null=True)  # Field name made lowercase.
    time = models.DateTimeField(blank=True, null=True)
    sid = models.TextField(db_column='SID', blank=True, null=True)  # Field name made lowercase.
    detail = models.TextField(db_column='detail', blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'tbox_data'


class BorgwardEngineDiagnostics(models.Model):
    problem_description = models.TextField(blank=True, null=True)
    parts = models.CharField(max_length=255, blank=True, null=True)
    performance = models.TextField(blank=True, null=True)
    frequency = models.IntegerField(blank=True, null=True)
    solution = models.TextField(blank=True, null=True)
    vehicle_system = models.CharField(max_length=255, blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'borgward_engine_diagnostics'

    def as_dict(self):
        return {
            "problem_description": self.problem_description,
            "parts": self.parts,
            "performance": self.performance,
            "solution": self.solution,
            "vehicle_system": self.vehicle_system
        }


class EngineDiagnosticsRecord(models.Model):
    time = models.DateTimeField(blank=True, null=True)
    location = models.CharField(max_length=255, blank=True, null=True)
    vehicle_model = models.CharField(max_length=255, blank=True, null=True)
    vin = models.CharField(max_length=255, blank=True, null=True)
    engine = models.CharField(max_length=255, blank=True, null=True)
    fault_code = models.CharField(max_length=255, blank=True, null=True)
    fault_phenomenon = models.CharField(max_length=255, blank=True, null=True)
    diagnosis = models.CharField(max_length=255, blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'engine_diagnostics_record'


class EngineFaultCode(models.Model):
    fault_code = models.CharField(max_length=255, blank=True, null=True)
    interpretation = models.CharField(max_length=255, blank=True, null=True)
    fault_cause = models.CharField(max_length=255, blank=True, null=True)
    diagnostic_scheme = models.CharField(max_length=255, blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'engine_fault_code'

    def engine_fault_code_dict(self):
        return {
            "fault_code": self.fault_code,
            "interpretation": self.interpretation,
            "fault_cause": self.fault_cause,
            "diagnostic_scheme": self.diagnostic_scheme
        }


class EngineFaultPhenomenon(models.Model):
    fault_phenomenon = models.CharField(max_length=255, blank=True, null=True)
    fault_cause = models.CharField(max_length=255, blank=True, null=True)
    diagnostic_scheme = models.CharField(max_length=255, blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'engine_fault_phenomenon'

data/forms.py
from django import forms

class EngineDiagnosticsForms(forms.Form):
    vehicle_model = forms.CharField(label='vehicle_model', max_length=100)
    vin = forms.CharField(label='vin', max_length=100)
    engine = forms.CharField(label='engine', max_length=100)


'''
    time = forms.DateTimeField(blank=True, null=True)
    location = forms.CharField(max_length=255, blank=True, null=True)
    # vehicle_model = forms.CharField(max_length=255, blank=True, null=True)
    vin = forms.CharField(max_length=255, blank=True, null=True)
    engine_type = forms.CharField(max_length=255, blank=True, null=True)
    engine_displacement = forms.CharField(max_length=255, blank=True, null=True)
    fault_code = forms.CharField(max_length=255, blank=True, null=True)
    fault_phenomenon = forms.CharField(max_length=255, blank=True, null=True)
    diagnosis = forms.CharField(max_length=255, blank=True, null=True)
'''

data/views.py
from django.shortcuts import render
from . import models
from .models import EngineDiagnosticsRecord
from . import forms
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.http import JsonResponse
from django.http import HttpResponse
import json
from django.http import HttpResponseRedirect
from .forms import EngineDiagnosticsForms

def index(request):
    context = {}
    return render(request, 'index.html', context)


def test_page(request):
    test_data = list(models.BorgwardEngineDiagnostics.objects.values('parts', 'problem_description'))
    context = {
        "data": test_data
    }
    return render(request, 'test_page.html', context)


# 根据提交的故障码和故障现象，查询到的结果形成json格式
def engine_fault_data_reload(request):
    if request.method == "GET":
        # 查询刚存入数据库的数据，记录里最后一条数据即为刚存入的数据
        fault_code = models.EngineDiagnosticsRecord.objects.values_list("fault_code", flat=True).last()
        fault_phenomenon = models.EngineDiagnosticsRecord.objects.values_list("fault_phenomenon", flat=True).last()
        # 转化字符串为列表
        fault_code = eval(fault_code)
        fault_phenomenon = eval(fault_phenomenon)

        # 根据最新的故障码查询维修方案
        fault_code_result = []
        for item in fault_code:
            # print('item=', item)
            fault_code_eachtime = models.EngineFaultCode.objects.values("fault_code", "interpretation",
                "fault_cause", "diagnostic_scheme").filter(fault_code=item)
            fault_code_result.extend(list(fault_code_eachtime))
        for dic in fault_code_result:
            # 合并故障码及其说明为一组数据
            dic["fault_phenomenon"] = dic["fault_code"] + " " + dic['interpretation']
            del dic['fault_code']
            del dic['interpretation']

        # 根据最新的故障现象查询维修方案
        fault_phenomenon_result = fault_code_result
        for item in fault_phenomenon:
            # print('item=', item)
            fault_phenomenon_eachtime = models.EngineFaultPhenomenon.objects.values("fault_phenomenon", "fault_cause",
                 "diagnostic_scheme").filter(fault_phenomenon=item)
            fault_phenomenon_result.extend(list(fault_phenomenon_eachtime)) # 故障现象的结果存入故障码结果后
        print("fault_phenomenon_result =", fault_phenomenon_result)
        return HttpResponse(json.dumps(fault_code_result, ensure_ascii=False), content_type="application/json")


# 取故障码和故障现象用于下拉选择，distinct去重
def diagnosis(request):
    data = models.EngineFaultCode.objects.values('fault_code').distinct()
    data2 = models.EngineFaultPhenomenon.objects.values('fault_phenomenon').distinct()

    context = {
        "fault_code": data,
        "fault_phenomenon": data2
    }
    # POST请求时，保存提交的记录到数据库
    if request.method == "GET":
        return render(request, "diagnosis.html", context)
    elif request.method == "POST":
        # 实例化record
        record = EngineDiagnosticsRecord()
        # 将用户输入数据存储
        record.time = request.POST["time"]
        record.location = request.POST["location"]
        record.vehicle_model = request.POST["vehicle_model"]
        record.vin = request.POST["vin"]
        record.engine = request.POST["engine"]
        record.fault_code = request.POST.getlist("fault_code")
        record.fault_phenomenon = request.POST.getlist("fault_phenomenon")
        # 保存
        record.save()
        return render(request, 'diagnosis.html', context)


# 测试用
def user_record(request):

    data = models.EngineDiagnosticsRecord.objects.filter.last()
    print("data=", data)
    context = {
        "record_data":data
    }
    return render(request, 'diagnosis.html', context)


# 全部的fault_code数据转化为json格式
def engine_fault_code_data(request):
    if request.method == "GET":
        objects = models.EngineFaultCode.objects.all()
        dic = [obj.engine_fault_code_dict() for obj in objects]
        return HttpResponse(json.dumps(dic, ensure_ascii=False), content_type="application/json")


# 显示各列表信息
def lists(request, table):
    # 从根据不同的请求，来获取相应的数据,并跳转至相应页面
    if table == 'tbox':
        raw_data = models.Tboxdata.objects.all()
        list_template = 'tbox_data.html'
        sub_title = 'tbox数据'

        # 通过GET方法从提交的URL来获取相应参数
        if request.method == 'GET':
            # 建立一个空的参数的字典
            kwargs = {}
            # 建立一个空的查询语句
            query = ''
            # 提交过来的GET值是一个迭代的键值对
            for key, value in request.GET.items():
                # 刨去其中的token和page选项
                if key != 'csrfmiddlewaretoken' and key != 'page':
                    # 由于线路和设备的外键均与node表格有关，当查询线路中的用户名称或设备信息中的使用部门时，可以直接通过以下方式跨表进行查找
                    if key == 'node':
                        kwargs['node__node_name__contains'] = value
                        # 该query用于页面分页跳转时，能附带现有的搜索条件
                        query += '&' + key + '=' + value
                    # 其余的选项均通过key来辨别
                    else:
                        kwargs[key + '__contains'] = value
                        # 该query用于页面分页跳转时，能附带现有的搜索条件
                        query += '&' + key + '=' + value
            # 通过元始数据进行过滤，过滤条件为健对值的字典
            data = raw_data.filter(**kwargs)
        # 如果没有从GET提交中获取信息，那么data则为元始数据
        else:
            data = raw_data

    # 将分页的信息传递到展示页面中去
    data_list, page_range, count, page_nums = pagination(request, data)
    # 建立context字典，将值传递到相应页面
    context = {
        'data': data_list,
        'table': table,
        'query': query,
        'page_range': page_range,
        'count': count,
        'page_nums': page_nums,
        'page_title': '基础数据',
        'sub_title': sub_title,
    }
    # 跳转到相应页面，并将值传递过去
    return render(request, list_template, context)


# 分页函数
def pagination(request, queryset, display_amount=15, after_range_num=5, before_range_num=4):
    # 按参数分页
    try:
        # 从提交来的页面获得page的值
        page = int(request.GET.get("page", 1))
        # 如果page值小于1，那么默认为第一页
        if page < 1:
            page = 1
        # 若报异常，则page为第一页
    except ValueError:
        page = 1
    # 引用Paginator类
    paginator = Paginator(queryset, display_amount)
    # 总计的数据条目
    count = paginator.count
    # 合计页数
    num_pages = paginator.num_pages
    # 当用户提交的页码不是整数时，提取第一页记录。当用户输入的页码太大时，只提取最后一页记录。
    objects = paginator.get_page(page)
    # 根据参数配置导航显示范围
    temp_range = paginator.page_range

    # 如果页面很小
    if (page - before_range_num) <= 0:
        # 如果总页面比after_range_num大，那么显示到after_range_num
        if temp_range[-1] > after_range_num:
            page_range = range(1, after_range_num + 1)
        # 否则显示当前页
        else:
            page_range = range(1, temp_range[-1] + 1)
    # 如果页面比较大
    elif (page + after_range_num) > temp_range[-1]:
        # 显示到最大页
        page_range = range(page - before_range_num, temp_range[-1] + 1)
    # 否则在before_range_num和after_range_num之间显示
    else:
        page_range = range(page - before_range_num + 1, page + after_range_num)
    # 返回分页相关参数
    return objects, page_range, count, num_pages

data/templates/addok.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>添加成功</title>
    <style>
        * {
            margin: 0;
            padding: 0;
        }
        a{
            text-decoration:none;
        }
    </style>
</head>
<body>
    <div>
        <p>添加信息成功</p>

    </div>
</body>
</html>

data/templates/can_data.html
{% extends "res_list.html" %}
{% block main %}
<li>can信息页面 未使用待完善</li>
{% endblock main %}

data/templates/index.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
	<head>
		<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
		<meta charset="utf-8" />
		<title>数据分析平台demo</title>

		<meta name="description" content="" />
		<meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0" />
		<!-- basic styles -->


		<!-- bootstrap & fontawesome -->
		<!-- jQuery -->
		<script type="text/javascript" charset="utf8" src="http://code.jquery.com/jquery-1.10.2.min.js"></script>
        <!--<script src="{%static 'assets/js/jquery-2.0.3.min.js'%}"></script>-->
		<link rel="stylesheet" href="{%static 'assets/css/bootstrap.min.css'%}"/>
		<link rel="stylesheet" href="{%static 'assets/css/font-awesome.min.css'%}" />
		<!-- text fonts -->
		<link rel="stylesheet" href="{%static 'assets/css/ace-fonts.css'%}" />
		<!-- ace styles -->
		<link rel="stylesheet" href="{%static 'assets/css/ace.min.css'%}" id="main-ace-style" />
		<link rel="stylesheet" href="{%static 'assets/css/ace-rtl.min.css'%}" />
		<link rel="stylesheet" href="{%static 'assets/css/ace-skins.min.css'%}" />
		<!--[if lte IE 9]>
		<link rel="stylesheet" href="{%static 'assets/css/ace-part2.min.css'%}" />
		<![endif]-->
		<link rel="stylesheet" href="{%static 'assets/css/ace-skins.min.css'%}" />
		<link rel="stylesheet" href="{%static 'assets/css/ace-rtl.min.css'%}" />
		<!--[if lte IE 8]>
        <link rel="stylesheet" href="{%static 'assets/css/ace-ie.min.css'%}" />
		<![endif]-->
		<!-- ace settings handler -->
		<script src="{%static 'assets/js/ace-extra.min.js'%}"></script>
		<!-- HTML5shiv and Respond.js for IE8 to support HTML5 elements and media queries -->
		<!--[if lte IE 9]>
		<script src="{%static 'assets/js/html5shiv.min.js'%}"></script>
		<script src="{%static 'assets/js/respond.min.js'%}"></script>
		<![endif]-->

		<!-- DataTables CSS -->
		<link rel="stylesheet" type="text/css" href="http://cdn.datatables.net/1.10.16/css/jquery.dataTables.css">
		<!-- DataTables -->
		<script type="text/javascript" charset="utf8" src="http://cdn.datatables.net/1.10.16/js/jquery.dataTables.js"></script>

		<!-- Latest compiled and minified CSS -->
		<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-select@1.13.8/dist/css/bootstrap-select.min.css">
		<!-- Latest compiled and minified JavaScript -->
		<script src="https://cdn.jsdelivr.net/npm/bootstrap-select@1.13.8/dist/js/bootstrap-select.min.js"></script>
		<!-- (Optional) Latest compiled and minified JavaScript translation files -->
		<script src="https://cdn.jsdelivr.net/npm/bootstrap-select@1.13.8/dist/js/i18n/defaults-*.min.js"></script>

		<link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/buttons/1.4.2/css/buttons.dataTables.css"/>
		<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jszip/2.5.0/jszip.js"></script>
		<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.32/vfs_fonts.js"></script>
		<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.32/pdfmake.js"></script>
		<script type="text/javascript" src="https://cdn.datatables.net/1.10.16/js/jquery.dataTables.js"></script>
		<script type="text/javascript" src="https://cdn.datatables.net/buttons/1.4.2/js/dataTables.buttons.js"></script>
		<script type="text/javascript" src="https://cdn.datatables.net/buttons/1.4.2/js/buttons.flash.js"></script>
		<script type="text/javascript" src="https://cdn.datatables.net/buttons/1.4.2/js/buttons.html5.js"></script>
		<script type="text/javascript" src="https://cdn.datatables.net/buttons/1.4.2/js/buttons.print.js"></script>


	</head>

	<body class="skin-1">
		<!-- #section:basics/navbar.layout -->
		<div id="navbar" class="navbar navbar-default">
			<script type="text/javascript">
				try{ace.settings.check('navbar' , 'fixed')}catch(e){}
			</script>

			<div class="navbar-container" id="navbar-container">
				<!-- #section:basics/sidebar.mobile.toggle -->
				<button type="button" class="navbar-toggle menu-toggler pull-left" id="menu-toggler">
					<span class="sr-only">Toggle sidebar</span>

					<span class="icon-bar"></span>

					<span class="icon-bar"></span>

					<span class="icon-bar"></span>
				</button>

				<!-- /section:basics/sidebar.mobile.toggle -->
				<div class="navbar-header pull-left">
					<!-- #section:basics/navbar.layout.brand -->
					<a href="#" class="navbar-brand">
						<small>
							<i class="fa fa-leaf"></i>
							数据分析平台
						</small>
					</a>
					<!-- /section:basics/navbar.layout.brand -->

					<!-- #section:basics/navbar.toggle -->

					<!-- /section:basics/navbar.toggle -->
                </div>

				<!-- #section:basics/navbar.dropdown -->
				<div class="navbar-buttons navbar-header pull-right" role="navigation">
					<ul class="nav ace-nav">

	<!-- #section:basics/navbar.user_menu -->
						<li class="light-blue">
							<a data-toggle="dropdown" href="#" class="dropdown-toggle">
								<span class="user-info">
                                <!--判断用户是否已经通过认证，如果通过则显示用户已登陆-->
                                    {% if user.is_authenticated %}
                                        用户选项
                                        <small>{{user.username}}已登录,</small>
										welcome
                                    {% else %}
                                        <small>未登录,</small>
										用户选项
                                    {% endif %}
								</span>

								<i class="icon-caret-down"></i>
							</a>

							<ul class="user-menu dropdown-menu-right dropdown-menu dropdown-yellow dropdown-caret dropdown-close">
                                <!--如果用户已经登陆则显示注销选项，否则显示登录选项-->
                                {% if user.is_authenticated %}
                                    <li>
									<a href="#">
										<i class="icon-off"></i>
										注销
									</a>
								</li>
								{% else %}
								<li>
									<a href="#">
										<i class="icon-user"></i>
										登录
									</a>
								</li>
								{% endif %}

                                <li class="divider"></li>
                                <li>
									<a href="#">
										<i class="icon-cog"></i>
										更改密码
									</a>
								</li>
							</ul>
						</li><!-- /section:basics/navbar.user_menu -->
					</ul>
				</div><!-- /section:basics/navbar.dropdown -->
			</div><!-- /.navbar-container -->
		</div><!-- /section:basics/navbar.layout -->

		<div class="main-container" id="main-container">
			<script type="text/javascript">
				try{ace.settings.check('main-container' , 'fixed')}catch(e){}
			</script>

			<div class="main-container-inner">
				<a class="menu-toggler" id="menu-toggler" href="#">
					<span class="menu-text"></span>
				</a>

			<!-- #section:basics/sidebar -->
			<div id="sidebar" class="sidebar responsive">
				<script type="text/javascript">
					try{ace.settings.check('sidebar' , 'fixed')}catch(e){}
				</script>

				<div class="sidebar-shortcuts" id="sidebar-shortcuts">
					<div class="sidebar-shortcuts-large" id="sidebar-shortcuts-large">
						<button class="btn btn-success">
							<i class="icon-signal"></i>
						</button>

						<button class="btn btn-info">
							<i class="icon-pencil"></i>
						</button>

						<!-- #section:basics/sidebar.layout.shortcuts -->
						<button class="btn btn-warning">
							<i class="icon-group"></i>
						</button>

						<button class="btn btn-danger">
							<i class="icon-cogs"></i>
						</button>
						<!-- /section:basics/sidebar.layout.shortcuts -->
					</div>

					<div class="sidebar-shortcuts-mini" id="sidebar-shortcuts-mini">
						<span class="btn btn-success"></span>
						<span class="btn btn-info"></span>
						<span class="btn btn-warning"></span>
						<span class="btn btn-danger"></span>
					</div>
				</div><!-- /.sidebar-shortcuts -->

                <ul class="nav nav-list">
					<li class="">
						<a href="{% url 'data:index' %}">
                            <i class="icon-dashboard"></i>
							<span class="menu-text"> 信息汇总 </span>
						</a>
						<b class="arrow"></b>
					</li>
					<!--如果相关路径在请求路径中，那么一下li class为active open -->
					{% if '/lists/' in request.path%}
					<li class="active open">
						{% else %}
					<li class="">
					{% endif %}
						<a href="#" class="dropdown-toggle">
							<i class="icon-list"></i>
							<span class="menu-text"> 基础数据 </span>
							<b class="arrow icon-angle-down"></b>
						</a>

						<ul class="submenu">
						<!--如果以下路径有tbox在请求路径中，那么节点信息的class li="active"-->
							{% if '/tbox/' in request.path %}
							<li class="active" >
								{% else %}
							<li class="">
                            {% endif %}
								<a href="{% url 'data:lists' table='tbox' %}">
									<i class="icon-double-angle-right"></i>tbox数据 &amp; 解析
								</a>
							</li>
							<li>
								<a href="{% url 'data:diagnosis' %}">
									<i class="icon-double-angle-right"></i>故障数据 & 分析
 								</a>
							</li>
							<li>
								<a href="#">
									<i class="icon-double-angle-right"></i>can 数据
								</a>
							</li>
						</ul>
					</li>

                     <li class="">
							<a href="#" class="dropdown-toggle">
								<i class="icon-file-alt"></i>
								<span class="menu-text">
									其他页面
								</span>

								<b class="arrow icon-angle-down"></b>
							</a>

							<ul class="submenu">
								<li>
									<a href="#">
										<i class="icon-double-angle-right"></i>建模分析
									</a>
								</li>

								<li>
									<a href="#">
										<i class="icon-double-angle-right"></i>可视化
									</a>
								</li>

								<li>
									<a href="{% url 'data:test_page'%}">
										<i class="icon-double-angle-right"></i>测试页面
									</a>
								</li>
							</ul>
						</li>
					</ul><!-- /.nav-list -->

                <!-- #section:basics/sidebar.layout.minimize收缩左侧导航的设置 -->
				<div class="sidebar-toggle sidebar-collapse" id="sidebar-collapse">
					<i class="icon-double-angle-left" data-icon1="icon-double-angle-left" data-icon2="icon-double-angle-right"></i>
				</div>

				<!-- /section:basics/sidebar.layout.minimize -->
				<script type="text/javascript">
					try{ace.settings.check('sidebar' , 'collapsed')}catch(e){}
				</script>
			</div>


			<div class="main-content">
				<!-- #section:basics/content.breadcrumbs面包屑导航栏 -->
				<div class="breadcrumbs" id="breadcrumbs">
					<script type="text/javascript">
						try{ace.settings.check('breadcrumbs' , 'fixed')}catch(e){}
					</script>

					<ul class="breadcrumb">
						<li>
                            <i class="icon-home home-icon"></i>
							<a href="#">Home</a>
						</li>
						<li><a href="#">{{ page_title }}</a></li>
						<li class="active">{{ sub_title }}</li>
					</ul><!-- /.breadcrumb -->
				</div>

				<div class="page-content">
					<div class="page-content-area">
						<div class="row">
							<div class="col-xs-12">
								<!-- PAGE CONTENT BEGINS -->
                                <!--设置页面内容-->
                                {% block container %}
								{% endblock %}
								<!-- PAGE CONTENT ENDS -->
							</div><!-- /.col -->
						</div><!-- /.row -->
					</div><!-- /.page-content-area -->
				</div><!-- /.page-content -->
			</div><!-- /.main-content -->

			<div class="ace-settings-container" id="ace-settings-container">
					<div class="btn btn-app btn-xs btn-warning ace-settings-btn" id="ace-settings-btn">
						<i class="icon-cog bigger-150"></i>
					</div>

					<div class="ace-settings-box" id="ace-settings-box">
						<div>
							<div class="pull-left">
								<select id="skin-colorpicker" class="hide">
									<option data-skin="default" value="#438EB9">#438EB9</option>
									<option data-skin="skin-1" value="#222A2D">#222A2D</option>
									<option data-skin="skin-2" value="#C6487E">#C6487E</option>
									<option data-skin="skin-3" value="#D0D0D0">#D0D0D0</option>
								</select>
							</div>
							<span>&nbsp; Choose Skin</span>
						</div>

						<div>
							<input type="checkbox" class="ace ace-checkbox-2" id="ace-settings-navbar" />
							<label class="lbl" for="ace-settings-navbar"> Fixed Navbar</label>
						</div>

						<div>
							<input type="checkbox" class="ace ace-checkbox-2" id="ace-settings-sidebar" />
							<label class="lbl" for="ace-settings-sidebar"> Fixed Sidebar</label>
						</div>

						<div>
							<input type="checkbox" class="ace ace-checkbox-2" id="ace-settings-breadcrumbs" />
							<label class="lbl" for="ace-settings-breadcrumbs"> Fixed Breadcrumbs</label>
						</div>

						<div>
							<input type="checkbox" class="ace ace-checkbox-2" id="ace-settings-rtl" />
							<label class="lbl" for="ace-settings-rtl"> Right To Left (rtl)</label>
						</div>

					</div>
				</div><!-- /#ace-settings-container -->
			</div><!-- /.main-container-inner -->

			<a href="#" id="btn-scroll-up" class="btn-scroll-up btn btn-sm btn-inverse">
				<i class="icon-double-angle-up icon-only bigger-110"></i>
			</a>
		</div><!-- /.main-container -->


        <!--引用基础的javascript元素-->
        {%  include 'javascript.html' %}
        <!--存放网页特定的javascript-->
        {% block page_javascript %}
        {% endblock %}

	</body>
</html>

data/templates/logout.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>logout-page</title>
</head>
<body>
    <p>logout</p>
</body>
</html>